version: "3.9"

services:
  api:
    build: .
    container_name: email_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build: .
    container_name: email_worker
    command: celery -A app.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: email_redis
    ports:
      - "6379:6379"
